feat(da): metrics
rollkit/centralized-sequencer pull request #11
Opened 2024-09-23 15:45 UTC by tuxcanfly

## Overview

2024-10-14 13:03 UTC, tzdybal requested changes
Left some comments.

2024-10-14 13:03 UTC, tzdybal commented on sequencing/metrics.go
> +	TransactionStatus metrics.Gauge
Please respond to this @tuxcanfly.

2024-10-25 14:53 UTC, tuxcanfly commented on sequencing/metrics.go
> +	TransactionStatus metrics.Gauge
Done 👍🏽

2024-10-25 14:55 UTC, tuxcanfly commented on sequencing/metrics.go
> +	}
Done 👍🏽

2024-11-01 14:57 UTC, gupadhyaya approved these changes

2024-11-04 08:17 UTC, tzdybal approved these changes
utACK

2024-11-04 08:38 UTC, merged